Add unit tests for GroupChatService functionality
StudieGrupp2Java/ChatApp pull request #92
Opened 2024-12-02 14:25 UTC by itsabunny

This pull request adds unit tests for the GroupChatService functionality, specifically targeting group chat behavior, message sending, and error handling.

2024-12-02 16:31 UTC, adrjo reviewed
coolt!

2024-12-03 08:17 UTC, Basti797 approved these changes
nice!

2024-12-03 08:24 UTC, adrjo requested changes

2024-12-03 08:24 UTC, adrjo commented on ChatServer/build.gradle
> -mainClassName = 'org.example.Main'
Denna måste vara kvar

2024-12-04 08:55 UTC, merged